{
  "hash": "975031efeeb5fcf6e0cd5d617d6c52d0",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: \"Take-home Exercise 3\"\nauthor: \"Stefanie Felicia\"\ndate: \"27 October, 2025\"\ndate-modified: \"last-modified\"\nexecute: \n  eval: true\n  echo: true\n  warning: false\n  freeze: true\n---\n\n## Background\n\n## Objective\n\n-   In this hands-on exercise, we'll be creating a geospatial explanatory model to predict HDB resale price from July to September 2024 using data from the whole year data (from July 2024 to June 2025). The focus of this take-home exercise analysis will be on four room HDB properties instead of all types fo HDB property.\n\n## The Data\n\nIn this hands, on we'll be using the following datasets:\n\n-   HDB Resale Flat Prices (from Jan-2017 onwards) taken from data.gov.sg\n-   Supermarket location data taken from <a href=\"https://data.gov.sg/datasets/d_8a77ee0446716b2ce475a587004afc73/view\">data.gov.sg</a>\n-   Bus stop location data taken from LTA Datamall\n-   Preschool location data taken from <a href=\"https://data.gov.sg/datasets/d_a72bcd23e208d995f3bd4eececeaca43/view\">data.gov.sg</a>\n-   Kindergaten location data taken from <a href=\"https://data.gov.sg/datasets/d_95aa63998d7de94dd4cb3e8e43a5f6d5/view\">data.gov.sg</a>\n-   Hakwer centre location data taken from <a href=\"https://data.gov.sg/datasets/d_ccca3606c337a5c386b9c88dc0dd08b6/view\">data.gov.sg</a>\n-   Eldercare service location data taken from <a href=\"https://data.gov.sg/datasets/d_1ee66bb5a41e00b5baadfe00224f649b/view\">data.gov.sg</a>\n-   Cleaned Master Plan 2019 Subzone (No Sea) dataset from Hands-on 2.\n-   MRT station location data taken from <a href=\"https://www.kaggle.com/datasets/shengjunlim/singapore-mrt-lrt-stations-with-coordinates\">Kaggle</a>. The original data is in xls format, but I tidied the data and changed the file format to csv as I could not open the xls file.\n\n## Import Libraries\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(olsrr, corrplot, httr, tidyverse, sf, tmap, jsonlite, progress, sfdep, GWmodel, Metrics, knitr, kableExtra, spatialRF, ggpubr, performance, car, rRColorBrewer, spdep, spatialreg)\n```\n:::\n\n\nLibraries used for this exercise are:\n\n-   olsrr: build ordinary least squares regression model\n\n-   httr: work with URL and HTTP\n\n-   tidyverse: designed to amke it easy to isntall and load multiple tidyverse packages\n\n-   sf: standardized way to encode and analyze spatial vector data\n\n-   tmap: draw thematic map\n\n-   jsonlite: json parser and generator\n\n-   progress: configurable progress bar\n\n-   sfdep: spatial depednence for sf\n\n-   GWmodel: techniques form a particular branch of spatial statistical\n\n-   SpatialModel: fit and summarize spatial model\n\n-   Metrics: implement metric for regression, time series, binary classification and classification\n\n-   ggpubr: provide easy to use function to customize ggplot2\n\n-   performance: utilities for computing measures to assess model quality\n\n-   car: provide function and tool for regression analysis\n\n-   rRColorBrewer: manage colors\n\n## Geocode HDB\n\nResale Data First, we'll import the HDB resale prices data using read_csv() and filter for 4 rooms HDB data from January to September 2025.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBresale <- read_csv(\"data/resale_price_from_jan2014.csv\") %>%\n  filter(flat_type == \"4 ROOM\") %>%\n  filter(month >= \"2025-01\" & month <= \"2025-09\")\n```\n:::\n\n\nNext, we'll also rename street names that has \"ST.\" into \"SAINT\"\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBresale$street_name <- gsub(\"ST\\\\.\", \"SAINT\", \n                              HDBresale$street_name)\n```\n:::\n\n\nNext, we'll be combining the block and street name column into addresses to be used for geocoding\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngeocode <- function(block, streetname) {\n  base_url <- \"https://onemap.gov.sg/api/common/elastic/search\"\n  address <- paste(block, streetname, sep = \" \")\n  query <- list(\"searchVal\" = address, \n                \"returnGeom\" = \"Y\",\n                \"getAddrDetails\" = \"N\", \n                \"pageNum\" = \"1\")\n  \n  res <- GET(base_url, query = query)\n  restext <- content(res, as=\"text\")\n  \n  output <- fromJSON(restext) %>%\n    as.data.frame %>%\n    select(results.LATITUDE, results.LONGITUDE)    \n  return(output)\n  } \n```\n:::\n\n\n::: callout-note\n-   `\"searchVal\" = address`: pass the address as searchVal in the query\n\n-   `\"returnGeom\" = \"Y\"`: send the query to OneMapSG search and return the geometry\n\n-   set `getAddreDetails = 'N'` since don't need all the address details\n\n-   `fromJSON(restext):` convert response from json format to text\n\n-   `select(results.LATITUDE, results.LATITUDE):` retain latitude and longitude for output\n:::\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBresale$LATITUDE <- 0\nHDBresale$LONGITUDE <- 0\nfor (i in 1:nrow(HDBresale)){\n  temp_output <- geocode(HDBresale[i,4], HDBresale[i, 5])\n  \nHDBresale$LATITUDE[i] <- temp_output$results.LATITUDE\nHDBresale$LONGITUDE[i] <- temp_output$results.LONGITUDE\n}\n```\n:::\n\n\n## Proximity Analysis\n\nIn this section, we'll count the number of geographic entities located within defined distance from each HDB properties.\n\nBefore performing proximity analysis, we need to make sure the input data need to be in sf object and they must be in the same projection coordinate system.\n\nIn our HDBresale variable, since it's still in tbl dataframe, we'll transform it into a sf object and adding in the coordinates and change the projected coordinate system.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBresale_sf <- HDBresale %>%\n  st_as_sf(coords = c(\"LONGITUDE\", \"LATITUDE\"), \n           crs=4326) %>%\n  st_transform(crs=3414)\n```\n:::\n\n\n### Import CBD Data\n\nNext, we'll import all dataset used for the analysis. First, we'll import the cleaned Master Plan 2019 Subzone (No Sea) dataset from Hands-on 2 exercise for to extract the CBD locations. We'll import the data using read_rds.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmap <- read_rds(\"data/mpsz_cl.rds\")\nst_crs(map)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nCoordinate Reference System:\n  User input: EPSG:3414 \n  wkt:\nPROJCRS[\"SVY21 / Singapore TM\",\n    BASEGEOGCRS[\"SVY21\",\n        DATUM[\"SVY21\",\n            ELLIPSOID[\"WGS 84\",6378137,298.257223563,\n                LENGTHUNIT[\"metre\",1]]],\n        PRIMEM[\"Greenwich\",0,\n            ANGLEUNIT[\"degree\",0.0174532925199433]],\n        ID[\"EPSG\",4757]],\n    CONVERSION[\"Singapore Transverse Mercator\",\n        METHOD[\"Transverse Mercator\",\n            ID[\"EPSG\",9807]],\n        PARAMETER[\"Latitude of natural origin\",1.36666666666667,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8801]],\n        PARAMETER[\"Longitude of natural origin\",103.833333333333,\n            ANGLEUNIT[\"degree\",0.0174532925199433],\n            ID[\"EPSG\",8802]],\n        PARAMETER[\"Scale factor at natural origin\",1,\n            SCALEUNIT[\"unity\",1],\n            ID[\"EPSG\",8805]],\n        PARAMETER[\"False easting\",28001.642,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8806]],\n        PARAMETER[\"False northing\",38744.572,\n            LENGTHUNIT[\"metre\",1],\n            ID[\"EPSG\",8807]]],\n    CS[Cartesian,2],\n        AXIS[\"northing (N)\",north,\n            ORDER[1],\n            LENGTHUNIT[\"metre\",1]],\n        AXIS[\"easting (E)\",east,\n            ORDER[2],\n            LENGTHUNIT[\"metre\",1]],\n    USAGE[\n        SCOPE[\"Cadastre, engineering survey, topographic mapping.\"],\n        AREA[\"Singapore - onshore and offshore.\"],\n        BBOX[1.13,103.59,1.47,104.07]],\n    ID[\"EPSG\",3414]]\n```\n\n\n:::\n:::\n\n\nWe'll filter for records that's in central region to get the CBD locations.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncbd_points <- map %>%\n  filter(REGION_N == \"CENTRAL REGION\")\n```\n:::\n\n\nWe'll check if all of the points are valid using st_is_valid()\n\n\n::: {.cell}\n\n```{.r .cell-code}\nst_is_valid(cbd_points)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n  [1]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE\n [13]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE\n [25]  TRUE  TRUE FALSE  TRUE  TRUE  TRUE FALSE  TRUE  TRUE  TRUE  TRUE  TRUE\n [37]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE\n [49]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE\n [61]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE\n [73]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE\n [85]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE\n [97]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE\n[109]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE\n[121]  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE  TRUE\n[133]  TRUE  TRUE\n```\n\n\n:::\n:::\n\n\nNext, we'll compute the distance between each HDB property to CBD and add a new column into the HDBresale_sf.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncbd_dist <- st_distance(HDBresale_sf, cbd_points)\n\nHDBresale_sf$cbd_distance <- apply(cbd_dist, 1, min) %>% as.numeric()\n```\n:::\n\n\nWe'll also check if all the distance are valid, all distance should not be less than 0.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsum(HDBresale_sf$cbd_distance < 0) \n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] 0\n```\n\n\n:::\n:::\n\n\n### Import Hawker Center Data\n\nNext, we'll import the hawker center location data using st_read and transform the projection system coordinate into 3414.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhawker <- st_read(\"data/HawkerCentresKML.kml\") %>%\n  st_transform(crs=3414)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `HAWKERCENTRE' from data source \n  `C:\\stefanie-fel\\ISSS626-GAA\\Take-home_Ex\\Take-home_Ex03\\data\\HawkerCentresKML.kml' \n  using driver `KML'\nSimple feature collection with 125 features and 2 fields\nGeometry type: POINT\nDimension:     XYZ\nBounding box:  xmin: 103.6974 ymin: 1.272716 xmax: 103.9882 ymax: 1.449017\nz_range:       zmin: 0 zmax: 0\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\nLike the previous dataset, we'll compute the distance from each HDB unit to nearest hawker centre using st_distance and add it as a column into the HDBresale_sf.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhawker_dist <- st_distance(HDBresale_sf, hawker)\n\nHDBresale_sf <- HDBresale_sf %>%\n  mutate(nearest_hawker = apply(hawker_dist, 1, min))\n```\n:::\n\n\n### Import Eldercare Data\n\nLike before, we'll import the eldercare data using st_reada and transform the data to 3414 coordinate reference system.\n\n\n::: {.cell}\n\n```{.r .cell-code}\neldercare <- st_read(\"data/EldercareServicesKML.kml\") %>%\n  st_transform(crs=3414)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `ELDERCARE' from data source \n  `C:\\stefanie-fel\\ISSS626-GAA\\Take-home_Ex\\Take-home_Ex03\\data\\EldercareServicesKML.kml' \n  using driver `KML'\nSimple feature collection with 133 features and 2 fields\nGeometry type: POINT\nDimension:     XYZ\nBounding box:  xmin: 103.7119 ymin: 1.271472 xmax: 103.9561 ymax: 1.439561\nz_range:       zmin: 0 zmax: 0\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\nNext, we'll compute the distance of each HDB property to the nearest eldercare service and add the column into the HDBresale_sf.\n\n\n::: {.cell}\n\n```{.r .cell-code}\neldercare_dist <- st_distance(HDBresale_sf, eldercare)\n\nHDBresale_sf <- HDBresale_sf %>%\n  mutate(nearest_eldercare = apply(eldercare_dist, 1, min))\n```\n:::\n\n\n### Import Supermarket Data\n\nLike before, we'll import the supermarket location data using st_read and transform the data to 3414 coordinate reference system.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsupermarket <- st_read(\"data/SupermarketsKML.kml\") %>%\n  st_transform(crs=3414)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `SUPERMARKETS' from data source \n  `C:\\stefanie-fel\\ISSS626-GAA\\Take-home_Ex\\Take-home_Ex03\\data\\SupermarketsKML.kml' \n  using driver `KML'\nSimple feature collection with 526 features and 2 fields\nGeometry type: POINT\nDimension:     XYZ\nBounding box:  xmin: 103.6258 ymin: 1.24715 xmax: 104.0036 ymax: 1.461526\nz_range:       zmin: 0 zmax: 0\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\nNext, we'll compute the distance of each HDB property to the nearest supermarket and add the column into the HDBresale_sf.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsupermarket_dist <- st_distance(HDBresale_sf, supermarket)\n\nHDBresale_sf <- HDBresale_sf %>%\n  mutate(nearest_supermarket = apply(supermarket_dist, 1, min))\n```\n:::\n\n\n### Import Kindergaten Data\n\nIn this section, we'll calculate how many kindergarten within 350 meters of each HDB property. We'll import the data using st_read() and transform the crs to 3414.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkindergarten <- st_read(\"data/Kindergartens.kml\") %>%\n  st_transform(crs=3414)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `KINDERGARTENS' from data source \n  `C:\\stefanie-fel\\ISSS626-GAA\\Take-home_Ex\\Take-home_Ex03\\data\\Kindergartens.kml' \n  using driver `KML'\nSimple feature collection with 448 features and 2 fields\nGeometry type: POINT\nDimension:     XYZ\nBounding box:  xmin: 103.6887 ymin: 1.247759 xmax: 103.9717 ymax: 1.455452\nz_range:       zmin: 0 zmax: 0\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\nNext, we'll calculate the number of kindergarten within 350 meters and add the results as a new column in HDBresale_sf.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nkindergarten_within_350m <- st_is_within_distance(\n  HDBresale_sf, kindergarten, dist = 350)\n\nHDBresale_sf <- HDBresale_sf %>%\n  mutate(kindergarten_350m = map_int(kindergarten_within_350m, length))\n```\n:::\n\n\n### Import Preschool Location Data\n\nin this section, we'll import the preschool dataset using st_read() and transform the projected coordinate system into 3414.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npreschool <- st_read(\"data/PreSchoolsLocation(1).kml\") %>%\n  st_transform(crs=3414)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `PRESCHOOLS_LOCATION' from data source \n  `C:\\stefanie-fel\\ISSS626-GAA\\Take-home_Ex\\Take-home_Ex03\\data\\PreSchoolsLocation(1).kml' \n  using driver `KML'\nSimple feature collection with 2290 features and 2 fields\nGeometry type: POINT\nDimension:     XYZ\nBounding box:  xmin: 103.6878 ymin: 1.247759 xmax: 103.9897 ymax: 1.462134\nz_range:       zmin: 0 zmax: 0\nGeodetic CRS:  WGS 84\n```\n\n\n:::\n:::\n\n\nNext, we'll count the number of preschool within 350 meter from each HDB property.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwithin_350m <- st_is_within_distance(\n  HDBresale_sf, preschool, dist = 350)\n\nHDBresale_sf <- HDBresale_sf %>%\n  mutate(preschool_350m = map_int(within_350m, length))\n```\n:::\n\n\n### Import Bus Stop Location\n\nNext, we want to calculate the number of bus stop within 350 meters of each HDB property.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbus_stop <- st_read(dsn = \"data/LTADataMall/\", \n                  layer = \"BusStop\") %>%\n  st_transform(crs = 3414)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nReading layer `BusStop' from data source \n  `C:\\stefanie-fel\\ISSS626-GAA\\Take-home_Ex\\Take-home_Ex03\\data\\LTADataMall' \n  using driver `ESRI Shapefile'\nSimple feature collection with 5172 features and 2 fields\nGeometry type: POINT\nDimension:     XY\nBounding box:  xmin: 3970.122 ymin: 26482.1 xmax: 48285.52 ymax: 52983.82\nProjected CRS: SVY21\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbus_within_350m <- st_is_within_distance(\n  HDBresale_sf, bus_stop, dist = 350)\n\nHDBresale_sf <- HDBresale_sf %>%\n  mutate(bus_350m = map_int(bus_within_350m, length))\n```\n:::\n\n\n### Import MRT Location\n\nNext, we'll calculate the distance of nearest MRT station from HDB property. We'll first import the data using read_csv().\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmrt <- read_csv(\"data/MRT Stations.csv\")\n```\n:::\n\n\nWe'll transform the tbl data frame into sf dataframe.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmrt_sf <- st_as_sf(mrt,\n                   wkt = \"geometry\",  \n                   crs = 4326)\n```\n:::\n\n\nNext, we'll transform the sf dataframe from 4326 to 3414 coordinate reference system.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmrt_sf <- st_transform(mrt_sf, 3414)\n```\n:::\n\n\nNext, we'll compute for the distance between each HDB property to the nearest MRT station\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmrt_dist <- st_distance(HDBresale_sf, mrt_sf)\n\nHDBresale_sf <- HDBresale_sf %>%\n  mutate(nearest_mrt = apply(mrt_dist, 1, min))\n```\n:::\n\n\n### Data Preparation for Existing Variables\n\nNext, we'll also extract only the years as the remaining_lease variable instead of containing both the year and month.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBresale_sf$remaining_lease <- as.integer(substr(HDBresale_sf$remaining_lease, 1, 2))\n```\n:::\n\n\nWe'll make turn storey_range column into nominal categorical variable instead of character variable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBresale_sf$storey_range <- factor(HDBresale_sf$storey_range,\n                         levels = c(\"01 TO 03\", \"04 TO 06\", \"07 TO 09\", \"10 TO 12\",\n                                    \"13 TO 15\", \"16 TO 18\", \"19 TO 21\", \"22 TO 24\",\n                                    \"25 TO 27\", \"28 TO 30\", \"31 TO 33\", \"34 TO 36\",\n                                    \"37 TO 39\", \"40 TO 42\", \"43 TO 45\", \"46 TO 48\",\n                                    \"49 TO 51\"),\n                         ordered = TRUE)\nclass(HDBresale_sf$storey_range)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n[1] \"ordered\" \"factor\" \n```\n\n\n:::\n:::\n\n\n## EDA\n\nIn this section, we'll look at the trend of each variable used for analysis. First, we'll check the resale_price variable.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nggplot(data=HDBresale_sf, \n       aes(x=`resale_price`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n\nAs can be seen, a lot of HDB property are sold in lower price (between \\$400,000 and \\$800,000), it is rare that property owner sells their HDB property for more than \\$800,000.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nPROX_ELDERLYCARE <- ggplot(data=HDBresale_sf, \n                           aes(x= `nearest_eldercare`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\")\n\nPROX_CBD <- ggplot(data=HDBresale_sf, \n                               aes(x= `cbd_distance`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\")\n\nPROX_HAWKER_MARKET <- ggplot(data=HDBresale_sf, \n                             aes(x= `nearest_hawker`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\")\n\nPROX_KINDERGARTEN <- ggplot(data=HDBresale_sf, \n                            aes(x= `kindergarten_350m`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\")\n\nPROX_PRESCHOOL <- ggplot(data=HDBresale_sf, \n                            aes(x= `preschool_350m`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\")\n\nPROX_SUPERMARKET <- ggplot(data=HDBresale_sf, \n                            aes(x= `nearest_supermarket`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\")\n\n\nPROX_REMAINING_LEASE <- ggplot(data=HDBresale_sf, \n                   aes(x= `remaining_lease`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\")\n\nPROX_BUS <- ggplot(data=HDBresale_sf, \n                   aes(x= `bus_350m`)) +\n  geom_histogram(bins=20, \n                 color=\"black\", \n                 fill=\"light blue\")\n\nggarrange(PROX_ELDERLYCARE, PROX_CBD, PROX_HAWKER_MARKET, PROX_KINDERGARTEN, PROX_PRESCHOOL, PROX_SUPERMARKET, PROX_REMAINING_LEASE, PROX_BUS, ncol = 5, nrow = 2)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-31-1.png){width=672}\n:::\n:::\n\n\nObservations from the independent variables:\n\n-   Most of the resold HDB properties are newly acquired, as most of them still have more than 90 years remaining lease year. However, some HDB property in the market are relatively older as they have 60 to 70 remaining lease years.\n\n-   A lot of HDB property are located in the CBD area, however most HDB are located around 3000 to 8000 meter from the CBD area.\n\n-   Most HDB are located near ameneties e.g. eldercare service, supermarket and hawker centre. Most HDB property are not built near kindergarten, but there are a few of preschools around the HDB property.\n\n### Statistical Point Map\n\nWe want to check the geospatial distribution of HDB resale price in SG. We'll visualize using tmap.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(map)+\n  tm_polygons() +\ntm_shape(HDBresale_sf) +  \n  tm_dots(fill = \"resale_price\",\n          fill_alpha = 0.6,\n          size = 0.5,\n          fill.scale = tm_scale_intervals(\n            style=\"quantile\")) \n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-32-1.png){width=672}\n:::\n:::\n\n\n### Multicollinearity Check\n\nBefore creating model, we'll check for the multicollinearity of each independent variables. If variables have high correlation with each other, we need to drop one fo the variable as the model may be unreliable and vague. First, let's drop the geometry field as the corrplot will pick up the geometry field if it's not dropped.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDB_numeric <- st_drop_geometry(HDBresale_sf)\ncolnames(HDB_numeric)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n [1] \"month\"               \"town\"                \"flat_type\"          \n [4] \"block\"               \"street_name\"         \"storey_range\"       \n [7] \"floor_area_sqm\"      \"flat_model\"          \"lease_commence_date\"\n[10] \"remaining_lease\"     \"resale_price\"        \"cbd_distance\"       \n[13] \"nearest_hawker\"      \"nearest_eldercare\"   \"nearest_supermarket\"\n[16] \"kindergarten_350m\"   \"preschool_350m\"      \"bus_350m\"           \n[19] \"nearest_mrt\"        \n```\n\n\n:::\n:::\n\n\nThe independent variables planned to be used in the model are the following:\n\n-   storey_range\n\n-   floor_area_sqm\n\n-   remaining_lease\n\n-   cbd_distance\n\n-   nearest_hawker\n\n-   nearest_eldercare\n\n-   nearest_supermarket\n\n-   kindergarten_350m\n\n-   preschool_350m\n\n-   bus_350m\n\n-   nearest_mrt\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncorrplot(cor(HDB_numeric[,c(10:19)]),\n         diag = FALSE, \n         order = \"AOE\",\n         tl.pos = \"td\", \n         tl.cex = 0.5, \n         method = \"number\", \n         type = \"upper\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-34-1.png){width=672}\n:::\n:::\n\n\nAs can be seen, all of the variables don't have high correlation with each other (\\< 0.8 correlation). So we can use all of the variables as predictors.\n\n## Build Multiple Linear Regression Model\n\nWe'll build the multiple regression model with lm() and use summary() to view the summary of the model.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresale_price.mlr <- lm(\n  formula = resale_price ~ floor_area_sqm + remaining_lease + cbd_distance  + \n    nearest_hawker + nearest_eldercare +\n    kindergarten_350m   +\n    bus_350m + nearest_mrt, \n  data=HDBresale_sf)\nsummary(resale_price.mlr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = resale_price ~ floor_area_sqm + remaining_lease + \n    cbd_distance + nearest_hawker + nearest_eldercare + kindergarten_350m + \n    bus_350m + nearest_mrt, data = HDBresale_sf)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-267996  -67318   -1575   58928  609852 \n\nCoefficients:\n                    Estimate Std. Error t value Pr(>|t|)    \n(Intercept)       -6.873e+04  1.703e+04  -4.035 5.50e-05 ***\nfloor_area_sqm     4.345e+03  1.571e+02  27.660  < 2e-16 ***\nremaining_lease    7.281e+03  7.539e+01  96.577  < 2e-16 ***\ncbd_distance      -2.925e+01  3.922e-01 -74.587  < 2e-16 ***\nnearest_hawker    -4.810e+01  2.115e+00 -22.738  < 2e-16 ***\nnearest_eldercare -1.463e+01  1.732e+00  -8.446  < 2e-16 ***\nkindergarten_350m  7.330e+03  9.652e+02   7.594 3.43e-14 ***\nbus_350m          -1.412e+03  3.593e+02  -3.929 8.58e-05 ***\nnearest_mrt       -6.531e+01  2.549e+00 -25.621  < 2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 93660 on 8670 degrees of freedom\nMultiple R-squared:  0.6603,\tAdjusted R-squared:   0.66 \nF-statistic:  2106 on 8 and 8670 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nFrom the summary statistics, the model can explain 66% of the HDB resale price and the model is significantly significant as p-value is less than 0.05. The variable used in the model are all significant as the p-value of each predictor are less than 0.05. Apart from that, we can see the model deviate from actual resale price, but that there's no bias in prediction (underprediction and overprediction)\n\n## Satisfying Requirements for Multiple Linear Regression\n\nNext, we'll check if the model satisfies the regression assumption, which are:\n\n-   Multicollinearity test: independent variables are not independent of each other, which makes it difficult to understand which variable influence the model.\n\n-   Non-linearity: independent and dependent variable need to have linear relation with each other\n\n-   Normality assumption: check if the model's residuals (difference between observed and predicted value) are normally distributed\n\n-   Spatial Autocorrelation: since we're building on a geographical referenced data, we need to check for spatial autocorrelation since regression models assume that observations (reisduals) are independent of each other.\n\n### Multicollinearity Test\n\nWe'll test for multicollinearity with check_collinearity and we'll plot the vif for easier understanding.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_collinearity(resale_price.mlr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n# Check for Multicollinearity\n\nLow Correlation\n\n              Term  VIF   VIF 95% CI adj. VIF Tolerance Tolerance 95% CI\n    floor_area_sqm 1.11 [1.09, 1.14]     1.05      0.90     [0.88, 0.92]\n   remaining_lease 1.12 [1.10, 1.15]     1.06      0.89     [0.87, 0.91]\n      cbd_distance 1.37 [1.33, 1.40]     1.17      0.73     [0.71, 0.75]\n    nearest_hawker 1.13 [1.10, 1.16]     1.06      0.89     [0.86, 0.91]\n nearest_eldercare 1.19 [1.17, 1.22]     1.09      0.84     [0.82, 0.86]\n kindergarten_350m 1.05 [1.03, 1.08]     1.02      0.95     [0.93, 0.97]\n          bus_350m 1.03 [1.02, 1.07]     1.02      0.97     [0.94, 0.98]\n       nearest_mrt 1.01 [1.00, 1.07]     1.01      0.99     [0.94, 1.00]\n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvif_model <- check_collinearity(resale_price.mlr)\nplot(vif_model)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-37-1.png){width=672}\n:::\n:::\n\n\nFrom the VIF plot, we can see that all of the predictors have no or very mild correlation with other predictors, so they don't affect the outcome (prediction) of the model. so we don't need to drop any of variable.\n\n### Test for Non-linearity\n\nWe'll also test if the independent variables have linear relationship with dependent variable. We'll be checking for non-linearity using the same function as multicollinearity test, but this time we add `check = \"linearity\"`\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_model(resale_price.mlr,\n            check = \"linearity\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-38-1.png){width=672}\n:::\n:::\n\n\nAs can be seen, the residuals failed the linearity test as there's a clear curve in the green line, which mean that the relationship between the predictors and resale price is not linear. Apart from that, the residuals spread increase at high fitted values. This means that statistical inference become unreliable (i.e. t-test become unreliable so predictor may become significant when it is not or vise versa, p-value is affected so significant variable can become significant when it is not).\n\nWe can check which variable is not linear by plotting crPlot().\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncbd_crplot <- crPlot(resale_price.mlr, variable = \"cbd_distance\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-39-1.png){width=672}\n:::\n\n```{.r .cell-code}\nfloor_area_crplot <- crPlot(resale_price.mlr, variable = \"floor_area_sqm\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-39-2.png){width=672}\n:::\n\n```{.r .cell-code}\nyear_crplot <- crPlot(resale_price.mlr, variable = \"remaining_lease\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-39-3.png){width=672}\n:::\n\n```{.r .cell-code}\nhawker_crplot <- crPlot(resale_price.mlr, variable = \"nearest_hawker\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-39-4.png){width=672}\n:::\n\n```{.r .cell-code}\nkindergarten_crplot <- crPlot(resale_price.mlr, variable = \"kindergarten_350m\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-39-5.png){width=672}\n:::\n\n```{.r .cell-code}\neldercare_crplot <- crPlot(resale_price.mlr, variable = \"nearest_eldercare\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-39-6.png){width=672}\n:::\n\n```{.r .cell-code}\nbus_crplot <- crPlot(resale_price.mlr, variable = \"bus_350m\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-39-7.png){width=672}\n:::\n\n```{.r .cell-code}\nmrt_crplot <- crPlot(resale_price.mlr, variable = \"nearest_mrt\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-39-8.png){width=672}\n:::\n\n```{.r .cell-code}\nggarrange(cbd_crplot, year_crplot, floor_area_crplot, hawker_crplot, kindergarten_crplot, eldercare_crplot, bus_crplot, mrt_crplot, ncol = 4, nrow = 2)\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-39-9.png){width=672}\n:::\n:::\n\n\ncbd_distance, nearest_hawker and nearest_mrt predictor show a downward trend from the linear component (purple line) and LOESS (blue dotted line). Only nearest_mrt show a consistent overlap between the linear component and LOESS line, so this means that only nearest_mrt have linear relationship with the dependent variable while nearest_hawker and cbd_distance don't have linear relationship with the dependent variable. One way to approach non-lineariy is that we can use log transformation to reduce skewness.\n\nfloor_area_sqm, remaining_lease and kindergarten_350m shows an upward trend, with remaining_lease and kindergarten_350m having linear relationship with the dependent variable (indicated by LOESS curve and linear component). Since the variable still show some skewness, we can use square root transformation on the variables to reduce the skewness.\n\nAnother way to ensure linearity fo model can also be done by transforming the dependent variable. In this case, we'll use log transformation as the EDA on the resale_price showed us a right tail distribution.\n\nNext, we'll calibrate the model with their transformation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresale_price.mlr <- lm(\n  formula = log(resale_price) ~  sqrt(floor_area_sqm) + sqrt(remaining_lease) + log(cbd_distance + 1)  + \n    log(nearest_hawker) + nearest_eldercare +\n    sqrt(kindergarten_350m)   +\n    bus_350m + log(nearest_mrt), \n  data=HDBresale_sf)\nsummary(resale_price.mlr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = log(resale_price) ~ sqrt(floor_area_sqm) + sqrt(remaining_lease) + \n    log(cbd_distance + 1) + log(nearest_hawker) + nearest_eldercare + \n    sqrt(kindergarten_350m) + bus_350m + log(nearest_mrt), data = HDBresale_sf)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.48810 -0.07831 -0.01313  0.07248  0.46257 \n\nCoefficients:\n                          Estimate Std. Error t value Pr(>|t|)    \n(Intercept)              1.154e+01  4.220e-02 273.452   <2e-16 ***\nsqrt(floor_area_sqm)     1.225e-01  3.732e-03  32.820   <2e-16 ***\nsqrt(remaining_lease)    1.583e-01  1.549e-03 102.213   <2e-16 ***\nlog(cbd_distance + 1)   -3.877e-02  4.408e-04 -87.949   <2e-16 ***\nlog(nearest_hawker)     -3.037e-02  1.944e-03 -15.620   <2e-16 ***\nnearest_eldercare       -2.322e-05  2.073e-06 -11.199   <2e-16 ***\nsqrt(kindergarten_350m) -6.449e-04  1.968e-03  -0.328   0.7431    \nbus_350m                 7.414e-04  4.439e-04   1.670   0.0949 .  \nlog(nearest_mrt)        -3.727e-02  1.802e-03 -20.683   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.1143 on 8670 degrees of freedom\nMultiple R-squared:  0.7169,\tAdjusted R-squared:  0.7166 \nF-statistic:  2745 on 8 and 8670 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nAfter the transformation, kindergarten_350m becomes insignificant predictor to predict resale_price,so we'll drop the variable. We can also observe that the prediction accuracy increased by 4% and the model is significant as the p-value is less than 0.05. We can also see Apart from that, we can see the model deviate from actual resale price, but that there's no bias in prediction (underprediction and overprediction).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrevised_mlr <- lm(\n  formula = log(resale_price) ~  sqrt(floor_area_sqm) + sqrt(remaining_lease) + log(cbd_distance + 1)  + \n    log(nearest_hawker) + nearest_eldercare  +\n    bus_350m + log(nearest_mrt), \n  data=HDBresale_sf)\nsummary(resale_price.mlr)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:\nlm(formula = log(resale_price) ~ sqrt(floor_area_sqm) + sqrt(remaining_lease) + \n    log(cbd_distance + 1) + log(nearest_hawker) + nearest_eldercare + \n    sqrt(kindergarten_350m) + bus_350m + log(nearest_mrt), data = HDBresale_sf)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.48810 -0.07831 -0.01313  0.07248  0.46257 \n\nCoefficients:\n                          Estimate Std. Error t value Pr(>|t|)    \n(Intercept)              1.154e+01  4.220e-02 273.452   <2e-16 ***\nsqrt(floor_area_sqm)     1.225e-01  3.732e-03  32.820   <2e-16 ***\nsqrt(remaining_lease)    1.583e-01  1.549e-03 102.213   <2e-16 ***\nlog(cbd_distance + 1)   -3.877e-02  4.408e-04 -87.949   <2e-16 ***\nlog(nearest_hawker)     -3.037e-02  1.944e-03 -15.620   <2e-16 ***\nnearest_eldercare       -2.322e-05  2.073e-06 -11.199   <2e-16 ***\nsqrt(kindergarten_350m) -6.449e-04  1.968e-03  -0.328   0.7431    \nbus_350m                 7.414e-04  4.439e-04   1.670   0.0949 .  \nlog(nearest_mrt)        -3.727e-02  1.802e-03 -20.683   <2e-16 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.1143 on 8670 degrees of freedom\nMultiple R-squared:  0.7169,\tAdjusted R-squared:  0.7166 \nF-statistic:  2745 on 8 and 8670 DF,  p-value: < 2.2e-16\n```\n\n\n:::\n:::\n\n\nNext, we'll check again if the model satisfy the linearity assumption.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_model(resale_price.mlr,\n            check = \"linearity\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-42-1.png){width=672}\n:::\n:::\n\n\nThe plot indicate that there's still a bit of non-linearity even after the variable are transformed as the green line is still not a straight line and does not follow the dotted line. However, this time, there is no sign of heteroskedacity as the residuals values do not have any pattern unlike before.\n\n### Test for Normality Assumption\n\nIn this section, we'll test for the normality assumption of the residuals for reliably compute confidence interval, p-value and statistical significance tests. We'll check by plotting its qqplot using check_normality(), but we'll add this argument `type = \"qq\"`.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(check_normality(resale_price.mlr), \n     type = \"qq\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-43-1.png){width=672}\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncheck_model(resale_price.mlr,\n            check= \"normality\")\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-44-1.png){width=672}\n:::\n:::\n\n\nFrom the qqplot and normality check, we can conclude that the model satisfies the normality assumption as the residuals follow the straight line in qqplot and from the second plot we can see the residual follow approximately normal distribution.\n\n### Spatial Autocorrelation\n\nBefore we check for spatial autocorrelation, we'll derive a new column in HDBresale_sf to calculate the residuals. We'll be using the residuals() function.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresidual_hdb <- residuals(resale_price.mlr)\nHDBresale_sf <- cbind(HDBresale_sf, residual_hdb) %>%\n  rename(model_residual = `residual_hdb`)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(RColorBrewer)\ntm_shape(map) +\n  tm_polygons(fill_alpha = 0.4) +\ntm_shape(HDBresale_sf) +  \n  tm_dots(\n    fill = \"model_residual\",\n    size = 0.7,\n    col = \"black\",\n    fill.scale = tm_scale(\n      n = 10,\n      values = rev(brewer.pal(11, \"RdBu\")),\n      style = \"quantile\",\n      midpoint = NA),\n    fill.legend = tm_legend(title = \"Residuals\")\n  ) + \n  tm_title(\"LM Residuals (Quantile Classification)\") +\n  tm_layout(legend.outside = TRUE) +\n  tm_view(set_zoom_limits = c(11,14))\n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-46-1.png){width=672}\n:::\n:::\n\n\nIt seems that there are spatial autocorrelation from the plot above (indicated by blue and red points on the map). We'll confirm by computing Moran's I.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBresale_sf <- HDBresale_sf %>% \n  mutate(\n    nb = st_dist_band(\n      st_geometry(geometry), \n                 upper = 1500),\n    wt = st_weights(\n      nb, style = \"W\"),\n    .before = 1) \n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1234)\nglobal_moran_perm(\n  HDBresale_sf$model_residual, \n  nb = HDBresale_sf$nb, \n  wt = HDBresale_sf$wt,\n  alternative = \"two.sided\", \n  nsim = 499)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMonte-Carlo simulation of Moran I\n\ndata:  x \nweights: listw  \nnumber of simulations + 1: 500 \n\nstatistic = 0.46044, observed rank = 500, p-value < 2.2e-16\nalternative hypothesis: two.sided\n```\n\n\n:::\n:::\n\n\nAs can be seen, the statistic is 0.46, which indicate a high spatial correlation and the the the findings are significant as p-value is less than 0.05.\n\n## Build HDB Resale Price Model with GWmodel\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbw.adaptive <- bw.gwr(\n  formula = log(resale_price) ~  sqrt(floor_area_sqm) + sqrt(remaining_lease) + log(cbd_distance + 1)  + \n    log(nearest_hawker) + nearest_eldercare  +\n    bus_350m + log(nearest_mrt), \n  data=HDBresale_sf, \n  approach=\"CV\", \n  kernel=\"gaussian\", \n  adaptive=TRUE, \n  longlat=FALSE)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\nTake a cup of tea and have a break, it will take a few minutes.\n          -----A kind suggestion from GWmodel development group\nAdaptive bandwidth: 5371 CV score: 99.75203 \nAdaptive bandwidth: 3327 CV score: 90.01183 \nAdaptive bandwidth: 2063 CV score: 83.13185 \nAdaptive bandwidth: 1282 CV score: 74.91956 \nAdaptive bandwidth: 799 CV score: 64.7395 \nAdaptive bandwidth: 501 CV score: 57.73536 \nAdaptive bandwidth: 316 CV score: 49.77402 \nAdaptive bandwidth: 202 CV score: 40.92748 \nAdaptive bandwidth: 131 CV score: 35.42502 \nAdaptive bandwidth: 88 CV score: 32.17934 \nAdaptive bandwidth: 60 CV score: 29.89346 \nAdaptive bandwidth: 44 CV score: Inf \nAdaptive bandwidth: 71 CV score: 30.99306 \nAdaptive bandwidth: 54 CV score: 29.20598 \nAdaptive bandwidth: 49 CV score: 28.88657 \nAdaptive bandwidth: 47 CV score: 28.70534 \nAdaptive bandwidth: 45 CV score: 28.55112 \nAdaptive bandwidth: 44 CV score: Inf \nAdaptive bandwidth: 45 CV score: 28.55112 \n```\n\n\n:::\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngwr.adaptive <- gwr.basic(\n  formula = log(resale_price) ~  sqrt(floor_area_sqm) + sqrt(remaining_lease) + log(cbd_distance + 1)  + \n    log(nearest_hawker) + nearest_eldercare   +\n    bus_350m + log(nearest_mrt), \n  data=HDBresale_sf, \n  bw=bw.adaptive, \n  kernel = 'gaussian', \n  adaptive=TRUE, \n  longlat = FALSE)\ngwr.adaptive\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n   ***********************************************************************\n   *                       Package   GWmodel                             *\n   ***********************************************************************\n   Program starts at: 2025-11-17 06:52:33.762359 \n   Call:\n   gwr.basic(formula = log(resale_price) ~ sqrt(floor_area_sqm) + \n    sqrt(remaining_lease) + log(cbd_distance + 1) + log(nearest_hawker) + \n    nearest_eldercare + bus_350m + log(nearest_mrt), data = HDBresale_sf, \n    bw = bw.adaptive, kernel = \"gaussian\", adaptive = TRUE, longlat = FALSE)\n\n   Dependent (y) variable:  resale_price\n   Independent variables:  floor_area_sqm remaining_lease cbd_distance nearest_hawker nearest_eldercare bus_350m nearest_mrt\n   Number of data points: 8679\n   ***********************************************************************\n   *                    Results of Global Regression                     *\n   ***********************************************************************\n\n   Call:\n    lm(formula = formula, data = data)\n\n   Residuals:\n     Min       1Q   Median       3Q      Max \n-0.48772 -0.07823 -0.01313  0.07252  0.46245 \n\n   Coefficients:\n                           Estimate Std. Error t value Pr(>|t|)    \n   (Intercept)            1.154e+01  4.219e-02 273.495   <2e-16 ***\n   sqrt(floor_area_sqm)   1.224e-01  3.719e-03  32.904   <2e-16 ***\n   sqrt(remaining_lease)  1.584e-01  1.531e-03 103.471   <2e-16 ***\n   log(cbd_distance + 1) -3.876e-02  4.392e-04 -88.249   <2e-16 ***\n   log(nearest_hawker)   -3.038e-02  1.943e-03 -15.632   <2e-16 ***\n   nearest_eldercare     -2.325e-05  2.071e-06 -11.230   <2e-16 ***\n   bus_350m               7.317e-04  4.429e-04   1.652   0.0986 .  \n   log(nearest_mrt)      -3.725e-02  1.800e-03 -20.690   <2e-16 ***\n\n   ---Significance stars\n   Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1 \n   Residual standard error: 0.1143 on 8671 degrees of freedom\n   Multiple R-squared: 0.7169\n   Adjusted R-squared: 0.7167 \n   F-statistic:  3137 on 7 and 8671 DF,  p-value: < 2.2e-16 \n   ***Extra Diagnostic information\n   Residual sum of squares: 113.2761\n   Sigma(hat): 0.1142574\n   AIC:  -13008.8\n   AICc:  -13008.78\n   BIC:  -21542.56\n   ***********************************************************************\n   *          Results of Geographically Weighted Regression              *\n   ***********************************************************************\n\n   *********************Model calibration information*********************\n   Kernel function: gaussian \n   Adaptive bandwidth: 45 (number of nearest neighbours)\n   Regression points: the same locations as observations are used.\n   Distance metric: Euclidean distance metric is used.\n\n   ****************Summary of GWR coefficient estimates:******************\n                                 Min.      1st Qu.       Median      3rd Qu.\n   Intercept              -2.6747e+02   1.0672e+01   1.1829e+01   1.4089e+01\n   sqrt(floor_area_sqm)   -9.3195e-01   8.2318e-02   1.1247e-01   1.4364e-01\n   sqrt(remaining_lease)  -4.6624e-01   1.2396e-01   1.6049e-01   2.0983e-01\n   log(cbd_distance + 1) -6.0818e+272  -3.0472e-01  -3.1057e-02   2.9525e-02\n   log(nearest_hawker)    -1.5266e+00  -5.3238e-02  -1.4329e-02   1.6850e-02\n   nearest_eldercare      -2.0765e-03  -5.8063e-05  -2.3259e-06   6.0310e-05\n   bus_350m               -1.8657e-02  -3.2894e-03   1.2019e-04   3.6477e-03\n   log(nearest_mrt)       -1.6069e+00  -1.0022e-01  -5.6660e-02  -2.1145e-02\n                                Max.\n   Intercept              2.4903e+02\n   sqrt(floor_area_sqm)   1.1227e+00\n   sqrt(remaining_lease)  4.4220e-01\n   log(cbd_distance + 1) 2.7131e+235\n   log(nearest_hawker)    1.7389e+00\n   nearest_eldercare      2.7000e-03\n   bus_350m               3.7100e-02\n   log(nearest_mrt)       1.6271e+00\n   ************************Diagnostic information*************************\n   Number of data points: 8679 \n   Effective number of parameters (2trace(S) - trace(S'S)): 726.7996 \n   Effective degrees of freedom (n-2trace(S) + trace(S'S)): 7952.2 \n   AICc (GWR book, Fotheringham, et al. 2002, p. 61, eq 2.33): -25036.53 \n   AIC (GWR book, Fotheringham, et al. 2002,GWR p. 96, eq. 4.22): -25691.44 \n   BIC (GWR book, Fotheringham, et al. 2002,GWR p. 61, eq. 2.34): -29756.71 \n   Residual sum of squares: 24.64851 \n   R-square value:  0.9384 \n   Adjusted R-square value:  0.9327693 \n\n   ***********************************************************************\n   Program stops at: 2025-11-17 06:53:06.316927 \n```\n\n\n:::\n:::\n\n\nAs can be seen, the R2 score is at 93%, which means that the model can explain 93% of the HDB resale price, the model is also significant. However, the model may not be as significant as the spatial autocrrelation is moderate, it can be seen from the coefficient summary of the cbd_distance is very big. So the model might not be as relavant. The variable that contribute the most to the model are floor_area_sqm and remaining_lease as they have highest estimate value and p-value lower than 0.05.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nHDBresale.adaptive <-\n  st_as_sf(gwr.adaptive$SDF) %>%\n  st_transform(crs=3414)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntm_shape(map)+\n  tm_polygons(fill_alpha = 0.1) +\ntm_shape(HDBresale.adaptive) +  \n  tm_dots(col = \"Local_R2\",\n          border.col = \"gray60\",\n          border.lwd = 1) \n```\n\n::: {.cell-output-display}\n![](Take-home_Ex03_files/figure-html/unnamed-chunk-52-1.png){width=672}\n:::\n:::\n\n\n```{}\n```\n\nThe model explains well the HDB preoperty's resale price overall, but they don't explain some resale price of HDB property in the north and west.\n\nSince the model isn't relevant, we can use other models such as SEM (Spatial Error Model), SDM (Spatial Durbin Model) and SAR (Spatial Autoregressive Model). However, since SEM is best model for explanatory model and it remove spatial autocorrelation in residuals (making coffeicient and p-value reliable), we'll caliberate this model.\n\nFirst, we'll start by create coordinates and create neighbour's list, then we'll convert the list to spatial weights and calibrate the model\n\n\n::: {.cell}\n\n```{.r .cell-code}\ncoords <- st_coordinates(st_centroid(HDBresale_sf))\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnb <- dnearneigh(coords, d1 = 0, d2 = 1500)\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nwt <- nb2listw(nb, style = \"W\")\n```\n:::\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nrevised_model <- errorsarlm(\n  formula = log(resale_price) ~  sqrt(floor_area_sqm) + sqrt(remaining_lease) + log(cbd_distance + 1)  + \n    log(nearest_hawker) + nearest_eldercare   +\n    bus_350m + log(nearest_mrt),\n  data = HDBresale_sf,\n  listw = wt,\n  method = \"eigen\"\n)\nsummary(revised_model)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\nCall:errorsarlm(formula = log(resale_price) ~ sqrt(floor_area_sqm) + \n    sqrt(remaining_lease) + log(cbd_distance + 1) + log(nearest_hawker) + \n    nearest_eldercare + bus_350m + log(nearest_mrt), data = HDBresale_sf, \n    listw = wt, method = \"eigen\")\n\nResiduals:\n        Min          1Q      Median          3Q         Max \n-0.57233724 -0.04871563 -0.00069994  0.04813583  0.36598626 \n\nType: error \nCoefficients: (asymptotic standard errors) \n                         Estimate  Std. Error  z value  Pr(>|z|)\n(Intercept)            1.1104e+01  6.7884e-02 163.5757 < 2.2e-16\nsqrt(floor_area_sqm)   1.3363e-01  2.7474e-03  48.6401 < 2.2e-16\nsqrt(remaining_lease)  1.8759e-01  1.2654e-03 148.2428 < 2.2e-16\nlog(cbd_distance + 1) -1.6088e-02  2.0454e-03  -7.8651 3.775e-15\nlog(nearest_hawker)   -1.2272e-02  1.7543e-03  -6.9953 2.647e-12\nnearest_eldercare     -1.4803e-05  2.7517e-06  -5.3795 7.467e-08\nbus_350m               2.2434e-03  3.2979e-04   6.8025 1.028e-11\nlog(nearest_mrt)      -6.8555e-02  1.7608e-03 -38.9339 < 2.2e-16\n\nLambda: 0.98524, LR test value: 6511.7, p-value: < 2.22e-16\nAsymptotic standard error: 0.0031903\n    z-value: 308.83, p-value: < 2.22e-16\nWald statistic: 95374, p-value: < 2.22e-16\n\nLog likelihood: 9769.245 for error model\nML residual variance (sigma squared): 0.0060661, (sigma: 0.077885)\nNumber of observations: 8679 \nNumber of parameters estimated: 10 \nAIC: -19518, (AIC for lm: -13009)\n```\n\n\n:::\n:::\n\n\nFrom the model, the log-likelihood seem to have better fit as the value is high (9769.245), as the AIc is also lower (-13,009), iy is better compared to the multiple linear regression model. The variable that contribute to predicting resale_price are floor_area_sqm and remaining_lease as the cofficient is high.\n\nNext, we'll test again for spatial autocorrelation.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresidual_revised <- residuals(revised_model)\n\nmoran.test(residual_revised, wt)\n```\n\n::: {.cell-output .cell-output-stdout}\n\n```\n\n\tMoran I test under randomisation\n\ndata:  residual_revised  \nweights: wt    \n\nMoran I statistic standard deviate = 9.4646, p-value < 2.2e-16\nalternative hypothesis: greater\nsample estimates:\nMoran I statistic       Expectation          Variance \n     9.381373e-03     -1.152339e-04      1.006771e-06 \n```\n\n\n:::\n:::\n\n\nAs can be seen, the Morans I value is close to 0, so there is no longer spatial autocorrelation in the model unlike the multiple linear regression model.\n",
    "supporting": [
      "Take-home_Ex03_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}