project:
  type: website

website:
  title: "ISSS626-GAA"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu:
        - text: "Hands-on Exercise 1a"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01.html"
        - text: "Hands-on Exercise 1b"
          href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01b.html"
        - text: "Hands-on Exercise 2a"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Exercise02a"
        - text: "Hands-on Exrcise 2b"
          href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Exercise02b"
      - text: "Take-home Exercise"
        menu:
        - text: "Take Home 1"
          href: "Take-home_Ex/Take-home_Ex01/Take-home_Ex01"
    right:
      - href: index.qmd
        text: Home
      - about.qmd

format:
  html:
    theme:
      - solar
    css: styles.css
    toc: true

editor: visual

